[submission] module05_student03_NguyenTienDat
MIMPython/MIMPython2023-Assignment pull request #69
Opened 2023-09-30 13:22 UTC by tdattm

2023-10-01 12:41 UTC, quanhoang-pm requested changes
Nội dung pull request không khớp với tiêu đề pull request (`...module05...`).

2023-10-01 13:46 UTC, tdattm commented
Em đã sửa ạ @quanhoang-pm

2023-10-01 14:00 UTC, quanhoang-pm requested changes

2023-10-01 14:00 UTC, quanhoang-pm commented on LICENSE
> +Copyright (c) 2023 Tien Dat
Có thêm file này trong repo chung của nhóm để làm gì?

2023-10-01 14:24 UTC, tdattm commented on LICENSE
> +Copyright (c) 2023 Tien Dat
em xóa rồi ạ

2023-10-02 02:20 UTC, quanhoang-pm requested changes
Đọc lại danh sách thay đổi hiện có trong pull request.

2023-10-02 05:20 UTC, tdattm commented
bây giờ file change chỉ còn mỗi sự thay đổi của module04 nữa thôi ạ (em đã xóa readme.md) @quanhoang-pm

2023-10-02 09:10 UTC, quanhoang-pm commented
Em liệt kê cho anh những thay đổi mà pull request này muốn thực hiện lên repo chính (xem phần `Files changed`) nhé.

2023-10-02 09:11 UTC, quanhoang-pm commented
Em liệt kê cho anh những thay đổi mà pull request này muốn thực hiện lên repo chính (xem phần `Files changed`) nhé.

2023-10-02 10:46 UTC, tdattm commented
pr đã thực hiện một số thay đổi module04, còn lại không thay đổi gì nữa ạ @quanhoang-pm

2023-10-02 13:33 UTC, quanhoang-pm approved these changes

2023-10-02 13:33 UTC, merged